
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[<>&"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"}[c]));
const param=n=>new URLSearchParams(location.search).get(n);
const catUrl=id=>`category.html?cat=${encodeURIComponent(id)}`;
const prodUrl=id=>`product.html?id=${encodeURIComponent(id)}`;
const Store={data:null,async load(){if(this.data)return this.data;const local=localStorage.getItem("elkass85alpha");if(local){this.data=JSON.parse(local);return this.data}const r=await fetch("data/store.json");this.data=await r.json();return this.data},save(d){this.data=d;localStorage.setItem("elkass85alpha",JSON.stringify(d))}};
function header(d){return `<header><div class="top"><div class="wrap top-inner"><a class="logo" href="index.html">ELKASS<span>OLESNO</span></a><div class="crumb">${esc(d.project.tagline)}</div><div class="search"><input placeholder="Szukaj produktów, kategorii, marek..."><button>⌕</button></div><div class="top-info"><span class="icon">☎</span><div>Zadzwoń<b>${esc(d.project.phone)}</b></div></div><div class="top-info"><span class="icon">⌖</span><div>Nasz salon<b>${esc(d.project.address)}</b></div></div><div class="account">Moje konto<b>Zaloguj</b></div><div class="cart">Koszyk<b>0 zł</b></div></div></div><nav class="menu"><div class="wrap menu-inner"><a class="cat-btn" href="#kategorie">☰ KATEGORIE</a><a class="red" href="#promocje">● PROMOCJE</a><a href="#">NOWOŚCI</a><a href="#">BESTSELLERY</a><a href="#">PRODUCENCI</a><a href="#">USŁUGI</a><a href="#">O NAS</a><a href="#kontakt">KONTAKT</a><a class="client" href="admin/index.html">STREFA KLIENTA</a></div></nav></header>`}
function footer(d){return `<footer class="footer" id="kontakt"><div class="wrap"><b>${esc(d.project.name)}</b><p>${esc(d.project.tagline)} · tel. ${esc(d.project.phone)} · ${esc(d.project.address)}</p></div></footer><div class="mobile-sticky"><a href="tel:${esc(d.project.phone).replaceAll(' ','')}">☎ Zadzwoń</a><a href="#findus">📍 Mapa</a><a href="#promocje">🔥 Promocje</a></div>`}
async function boot(){const d=await Store.load();if(!document.body.classList.contains("admin-shell")){document.body.insertAdjacentHTML("afterbegin",header(d));document.body.insertAdjacentHTML("beforeend",footer(d))}const p=document.body.dataset.page;if(p==="home")home(d);if(p==="category")category(d);if(p==="product")product(d)}
function active(d,id){const s=(d.homeSections||[]).find(x=>x.id===id);return !s||s.active!==false}
function home(d){const cats=d.categories.filter(c=>c.home&&c.active);const promos=d.products.filter(p=>p.promo&&p.active).slice(0,4);const featured=d.products.filter(p=>p.featured&&p.active).slice(0,4);const main=promos[0]||d.products[0];let html="";
if(active(d,"hero")) html+=`<section class="wrap hero"><div class="hero-left"><div class="kicker">Witamy w ELKASS Olesno</div><h1>RTV / AGD</h1><div class="hero-sub">Najlepsze marki · fachowe doradztwo · lokalny salon</div><div class="hero-icons"><div class="hero-icon"><span>♢</span>Fachowe<br>doradztwo</div><div class="hero-icon"><span>▱</span>Transport<br>i montaż</div><div class="hero-icon"><span>◎</span>Autoryzowany<br>sprzedawca</div><div class="hero-icon"><span>♧</span>Serwis<br>i wsparcie</div></div><a class="btn red" href="#promocje">ZOBACZ PROMOCJE</a> <a class="btn ghost" href="#kategorie">ZOBACZ PRODUKTY</a></div><div class="hero-product"><img src="${esc(main.image)}" alt=""></div></section>`;
if(active(d,"categories")) html+=`<section class="wrap cat-row" id="kategorie">${cats.map(homeCat).join("")}</section>`;
if(active(d,"promotions")) html+=`<section class="wrap section white" id="promocje"><div class="section-title"><h2>Promocje</h2><a href="#">Zobacz wszystkie →</a></div><div class="promo-grid">${promos.map(productCard).join("")}</div></section>`;
if(active(d,"trustbar")) html+=`<section class="wrap trust"><div><span>↻</span><p><b>30 dni na zwrot</b><small>Zakupy bez ryzyka</small></p></div><div><span>♢</span><p><b>Gwarancja producenta</b><small>Sprzęt z pewnego źródła</small></p></div><div><span>▱</span><p><b>Szybki transport</b><small>Dostawa i montaż</small></p></div><div><span>▣</span><p><b>Raty i płatności</b><small>Wygodne formy zakupu</small></p></div></section>`;
if(active(d,"featured")) html+=`<section class="wrap section white"><div class="section-title"><h2>Najczęściej wybierane</h2></div><div class="promo-grid">${featured.map(productCard).join("")}</div></section>`;
if(active(d,"why")) html+=`<section class="wrap section white split"><div class="box"><h2>Dlaczego warto kupować w ELKASS?</h2><div class="stats"><div class="stat"><b>25+</b>lat doświadczenia</div><div class="stat"><b>${esc(d.project.googleRating)}</b>ocena Google</div><div class="stat"><b>100%</b>lokalnie</div><div class="stat"><b>RTV</b>AGD / Serwis</div></div></div><div class="darkbox"><h2>Zaufanie lokalnych klientów</h2><ul><li>Fachowe doradztwo</li><li>Transport i montaż</li><li>Pomoc po zakupie</li></ul></div></section>`;
if(active(d,"google")) html+=`<section class="wrap section white"><div class="section-title"><h2>Opinie Google</h2><a href="${esc(d.project.googleLink)}">Zobacz w Google →</a></div><div class="reviews">${d.reviews.google.map(r=>review(r,"Google")).join("")}</div></section>`;
if(active(d,"reviews")) html+=`<section class="wrap section white"><div class="section-title"><h2>Opinie klientów z Olesna i okolic</h2></div><div class="reviews">${d.reviews.local.map(r=>review(r,"Klient ELKASS")).join("")}</div></section>`;
if(active(d,"brands")) html+=`<section class="wrap section brands"><div class="brand-track">${[...d.brands,...d.brands].map(b=>`<span>${esc(b)}</span>`).join("")}</div></section>`;
if(active(d,"gallery")) html+=`<section class="wrap section white"><div class="section-title"><h2>Galeria ELKASS</h2></div><div class="gallery">${d.gallery.map(g=>`<div class="gal"><img src="${esc(g.image)}"><b>${esc(g.title)}</b></div>`).join("")}</div></section>`;
if(active(d,"findus")) html+=`<section class="wrap section white findus" id="findus"><div class="box"><h2>Znajdź nas</h2><p><b>${esc(d.project.name)}</b><br>${esc(d.project.address)}</p><p><a class="btn red" href="tel:${esc(d.project.phone).replaceAll(' ','')}">Zadzwoń: ${esc(d.project.phone)}</a></p></div><div class="mapfake">Mapa / wyznacz trasę</div></section>`;
$("#app").innerHTML=html;
}
function homeCat(c){return `<a class="home-cat" href="${catUrl(c.id)}"><div class="pic">${esc(c.icon)}</div><div><b>${esc(c.name)}</b><p>${esc(c.description)}</p></div><div class="arr">→</div></a>`}
function productCard(p){return `<a class="promo" href="${prodUrl(p.id)}"><span class="discount">${esc(p.discount||"Oferta")}</span><img src="${esc(p.image)}"><div><b>${esc(p.name)}</b><div class="price"><strong>${esc(p.price)}</strong>${p.oldPrice?`<s>${esc(p.oldPrice)}</s>`:""}</div><button class="mini-btn">ZOBACZ</button></div></a>`}
function review(t,a){return `<div class="review"><div class="stars">★★★★★</div><p>${esc(t)}</p><b>${esc(a)}</b></div>`}
function category(d){const id=param("cat")||"rtv";const c=d.categories.find(x=>x.id===id)||d.categories[0];const children=(c.children||[]).map(cid=>d.categories.find(x=>x.id===cid)).filter(Boolean);const prods=d.products.filter(p=>p.category===c.id);$("#app").innerHTML=`<section class="wrap product-section"><div class="kicker">Oferta sklepu</div><h1>${esc(c.name)}</h1><p>${esc(c.description)}</p>${children.length?`<div class="cat-row">${children.map(homeCat).join("")}</div>`:""}<div class="section-title"><h2>Produkty</h2></div>${prods.length?`<div class="promo-grid">${prods.map(productCard).join("")}</div>`:`<p>Wybierz podkategorię albo dodaj produkt w panelu.</p>`}</section>`}
function product(d){const id=param("id")||d.products[0].id;const p=d.products.find(x=>x.id===id)||d.products[0];const similar=d.products.filter(x=>x.id!==p.id&&x.category===p.category).slice(0,4);$("#app").innerHTML=`<section class="wrap product-hero"><div><img src="${esc(p.image)}"></div><div><div class="kicker">${esc(p.category)}</div><h1>${esc(p.name)}</h1><div class="price"><strong>${esc(p.price)}</strong>${p.oldPrice?`<s>${esc(p.oldPrice)}</s>`:""}</div><div class="chips">${(p.badges||[]).map(b=>`<span class="chip">${esc(b)}</span>`).join("")}</div><p>● Dostępny: ${esc(p.stock)} szt.</p><button class="btn red" onclick="window.print()">Drukuj / PDF</button></div></section><section class="wrap product-section"><h2>Parametry techniczne</h2><table class="spec">${Object.entries(p.specs||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join("")}</table></section><section class="wrap product-section"><h2>Opis produktu</h2><p>${esc(p.description)}</p></section><section class="wrap product-section"><h2>Porada specjalisty ELKASS</h2><div class="advisor">${esc(p.advisor)}</div></section><section class="wrap product-section"><h2>Opinie klientów</h2><div class="reviews">${(d.reviews.local||[]).slice(0,3).map(r=>review(r,"Klient z Olesna")).join("")}</div></section><section class="wrap product-section"><h2>Podobne produkty</h2>${similar.length?`<div class="promo-grid">${similar.map(productCard).join("")}</div>`:`<p>Brak podobnych produktów w tej kategorii.</p>`}</section>`}
document.addEventListener("DOMContentLoaded",boot);
