
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[<>&"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"}[c]));
const param=n=>new URLSearchParams(location.search).get(n);
const catUrl=id=>`category.html?cat=${encodeURIComponent(id)}`;
const prodUrl=id=>`product.html?id=${encodeURIComponent(id)}`;
const Store={data:null,async load(){if(this.data)return this.data;const local=localStorage.getItem("elkass_match_store");if(local){this.data=JSON.parse(local);return this.data}const r=await fetch("data/store.json");this.data=await r.json();return this.data},save(d){this.data=d;localStorage.setItem("elkass_match_store",JSON.stringify(d))}};

function header(d){return `<header><div class="top"><div class="wrap top-inner"><a class="logo" href="index.html">ELKASS<span>OLESNO</span></a><div class="crumb">RTV / AGD / AGD DO ZABUDOWY</div><div class="search"><input placeholder="Szukaj produktów, kategorii, marek..."><button>⌕</button></div><div class="top-info"><span class="icon-gold">☎</span><div>Zadzwoń do nas<b>${esc(d.project.phone)}</b></div></div><div class="top-info"><span class="icon-gold">⌖</span><div>Nasz salon<b>${esc(d.project.address)}</b></div></div><div class="account">Moje konto<b>Zaloguj się</b></div><div class="cart">Koszyk<b>Koszyk</b></div></div></div><nav class="menu"><div class="wrap menu-inner"><a class="cat-btn" href="#kategorie">☰ KATEGORIE</a><a class="red" href="#promocje">⦿ PROMOCJE</a><a href="#">NOWOŚCI</a><a href="#">BESTSELLERY</a><a href="#">PRODUCENCI</a><a href="#">USŁUGI</a><a href="#">O NAS</a><a href="#kontakt">KONTAKT</a><a class="client" href="admin/index.html">♙ STREFA KLIENTA</a></div></nav></header>`}
function footer(d){return `<footer class="footer" id="kontakt"><div class="wrap"><b>${esc(d.project.name)}</b><p>${esc(d.project.tagline)} · tel. ${esc(d.project.phone)} · ${esc(d.project.address)}</p></div></footer>`}

async function boot(){const d=await Store.load();if(!document.body.classList.contains("admin-shell")){document.body.insertAdjacentHTML("afterbegin",header(d));document.body.insertAdjacentHTML("beforeend",footer(d))}const page=document.body.dataset.page;if(page==="home")home(d);if(page==="category")category(d);if(page==="product")product(d)}
function home(d){const cats=d.categories.filter(c=>c.home&&c.active);const promos=d.products.filter(p=>p.promo&&p.active).slice(0,4);const main=promos[0]||d.products[0];$("#app").innerHTML=`<section class="wrap hero"><div class="hero-left"><div class="kicker">WITAMY W ELKASS OLESNO</div><h1>RTV / AGD</h1><div class="hero-sub">NAJLEPSZE MARKI • NAJLEPSZE CENY • NAJLEPSZA OBSŁUGA</div><div class="hero-icons"><div class="hero-icon"><span>♢</span>GWARANCJA<br>NAJNIŻSZEJ CENY</div><div class="hero-icon"><span>▱</span>DARMOWA DOSTAWA<br>OD 500 ZŁ</div><div class="hero-icon"><span>◎</span>AUTORYZOWANY<br>SPRZEDAWCA</div><div class="hero-icon"><span>♧</span>PROFESJONALNY<br>SERWIS</div></div><div><a class="btn" href="#promocje">ZOBACZ PROMOCJE</a> <a class="btn ghost" href="#kategorie">ZOBACZ PRODUKTY</a></div></div><div class="hero-product"><img src="${esc(main.media?.main||main.images?.[0])}" alt=""><div class="dots"><i></i><i></i><i></i><i></i><i></i></div></div></section><section class="wrap cat-row" id="kategorie">${cats.slice(0,3).map(homeCat).join("")}</section><section class="wrap" id="promocje"><div class="section-title"><h2>PROMOCJE</h2><a href="#">ZOBACZ WSZYSTKIE PROMOCJE →</a></div><div class="promo-grid">${promos.map(promoCard).join("")}</div><div class="benefit-bar"><div class="benefit"><span>↻</span><div><b>30 dni na zwrot</b><small>Zakupy bez ryzyka</small></div></div><div class="benefit"><span>♢</span><div><b>Gwarancja producenta</b><small>24 miesiące</small></div></div><div class="benefit"><span>▱</span><div><b>Szybka wysyłka</b><small>Zamów do 14:00</small></div></div><div class="benefit"><span>▣</span><div><b>Bezpieczne płatności</b><small>BLIK, karta, przelew, raty</small></div></div></div></section><section class="wrap white-zone split"><div class="recommended"><h2>POLECANE PRODUKTY</h2><div class="tabs"><b>Bestsellery</b><b>Nowości</b><b>Polecane</b></div><div class="promo-grid">${d.products.slice(0,3).map(p=>`<div class="product-card-lite"></div>`).join("")}</div></div><div class="why"><h2>DLACZEGO ELKASS?</h2><ul><li>Ponad 20 lat doświadczenia</li><li>Profesjonalne doradztwo</li><li>Indywidualne podejście do klienta</li></ul><div class="laurel">20 LAT</div></div></section>`}
function homeCat(c){return `<a class="home-cat" href="${catUrl(c.id)}"><div class="pic">${esc(c.icon||"▭")}</div><div><b>${esc(c.name)}</b><p>${esc(c.description)}</p></div><div class="arr">→</div></a>`}
function promoCard(p){return `<a class="promo" href="${prodUrl(p.id)}"><span class="discount">${esc(p.discount)}</span><img src="${esc(p.media?.promo||p.images?.[0])}"><div class="promo-info"><b>${esc(p.name)}</b><div class="price"><strong>${esc(p.price)}</strong><s>${esc(p.oldPrice||"")}</s></div><button class="mini-btn">ZOBACZ</button></div></a>`}
function category(d){const id=param("cat")||"rtv";const c=d.categories.find(x=>x.id===id)||d.categories[0];const children=(c.children||[]).map(cid=>d.categories.find(x=>x.id===cid)).filter(Boolean);const prods=d.products.filter(p=>p.category===c.id);$("#app").innerHTML=`<section class="wrap category-page"><div class="kicker">OFERTA SKLEPU</div><h1>${esc(c.name)}</h1><p>${esc(c.description)}</p>${children.length?`<div class="cat-row">${children.map(homeCat).join("")}</div>`:""}<div class="section-title"><h2>PRODUKTY</h2></div>${prods.length?`<div class="promo-grid">${prods.map(promoCard).join("")}</div>`:`<p>Wybierz podkategorię albo dodaj produkt w panelu.</p>`}</section>`}
function product(d){const id=param("id")||d.products[0].id;const p=d.products.find(x=>x.id===id)||d.products[0];$("#app").innerHTML=`<section class="wrap product-hero"><div><img src="${esc(p.media?.main||p.images?.[0])}"></div><div><div class="kicker">${esc(p.category)}</div><h1>${esc(p.name)}</h1><div class="price"><strong>${esc(p.price)}</strong><s>${esc(p.oldPrice||"")}</s></div><div class="chips">${(p.badges||[]).map(b=>`<span class="chip">${esc(b)}</span>`).join("")}</div><p>${esc(p.description)}</p><h2>Porada specjalisty ELKASS</h2><p>${esc(p.advisor||"Zapytaj doradcę ELKASS.")}</p><button class="btn" onclick="window.print()">DRUKUJ / PDF</button></div></section><section class="wrap category-page"><h2>Parametry techniczne</h2><table class="spec">${Object.entries(p.specs||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join("")}</table></section>`}
document.addEventListener("DOMContentLoaded",boot);
