
async function load(){const local=localStorage.getItem("elkass81_store");if(local)return JSON.parse(local);const r=await fetch("../data/store.json");return await r.json()}
function save(d){localStorage.setItem("elkass81_store",JSON.stringify(d));alert("Zapisano lokalnie. W etapie III zapis będzie w Supabase.")}
const slug=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ł/g,"l").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")
function parseProducer(raw){const specs={},features=[],desc=[];String(raw||"").split(/\n+/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const i=line.indexOf(":");if(i>0&&i<75){specs[line.slice(0,i).trim()]=line.slice(i+1).trim();return}const m=line.match(/^(.{3,55}?)\s[-–—]\s(.+)$/);if(m){features.push(m[1].trim());desc.push(m[1].trim()+": "+m[2].trim());return}desc.push(line)});return{specs,features,description:desc.join("\n\n")}}
async function productPage(){const d=await load();cats.innerHTML=d.categories.filter(c=>c.parent).map(c=>`<option value="${c.id}">${c.name}</option>`).join("");saveBtn.onclick=()=>{const parsed=parseProducer(raw.value);const id=slug(name.value);const img=images.value?images.value.split(",").map(x=>x.trim()).filter(Boolean):["assets/products/tv.svg"];const item={id,name:name.value,category:cats.value,price:price.value,oldPrice:oldPrice.value,discount:discount.value,status:"available",stock:Number(stock.value||0),promo:promo.checked,promoType:promoType.value,featured:featured.checked,badges:badges.value.split(",").map(x=>x.trim()).filter(Boolean),features:features.value?features.value.split(",").map(x=>x.trim()).filter(Boolean):parsed.features,advisor:advisor.value,specs:parsed.specs,description:description.value||parsed.description,media:{original:"media-originals/"+id+".jpg",main:img[0],thumb:img[0],promo:img[0],pdf:img[0]},images:img,active:active.checked};d.products=d.products.filter(p=>p.id!==id);d.products.push(item);save(d)}}
async function categoriesPage(){const d=await load();list.innerHTML=d.categories.map(c=>`<div class="admin-card"><b>${c.icon} ${c.name}</b><p>${c.parent||"główna"} · ${c.id}</p></div>`).join("");saveCat.onclick=()=>{d.categories.push({id:slug(catName.value),name:catName.value,icon:icon.value||"📦",description:catDesc.value,parent:parent.value||null,children:[],active:true,home:home.checked});save(d)}}
async function homePage(){const d=await load();sections.innerHTML=(d.homeSections||[]).sort((a,b)=>a.order-b.order).map(s=>`<div class="admin-card"><b>${s.active?"🟢":"⚪"} ${s.title}</b><p>${s.type}</p><button onclick="toggleSection('${s.id}')">${s.active?"Ukryj":"Aktywuj"}</button></div>`).join("")}
async function toggleSection(id){const d=await load();const s=d.homeSections.find(x=>x.id===id);if(s){s.active=!s.active;save(d);homePage()}}
async function settingsPage(){const d=await load();theme.value=d.settings.theme||"premium-dark";saveSettings.onclick=()=>{d.settings.theme=theme.value;save(d)}}
