
async function load(){const local=localStorage.getItem("elkass85rc");if(local)return JSON.parse(local);const r=await fetch("../data/store.json");return await r.json()}
function save(d){localStorage.setItem("elkass85rc",JSON.stringify(d));alert("Zapisano lokalnie. W produkcji zapis przejmie Supabase.")}
const slug=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ł/g,"l").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")
function parseProducer(raw){const specs={},features=[],desc=[];String(raw||"").split(/\n+/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const i=line.indexOf(":");if(i>0&&i<80){specs[line.slice(0,i).trim()]=line.slice(i+1).trim();return}const m=line.match(/^(.{3,55}?)\s[-–—]\s(.+)$/);if(m){features.push(m[1].trim());desc.push(`${m[1].trim()}: ${m[2].trim()}`);return}desc.push(line)});return{specs,features,description:desc.join("\n\n")}}
function autoBadges(text){const t=String(text||"").toLowerCase();const out=[];if(/smart|android|tizen/.test(t))out.push("Smart TV");if(/hdr/.test(t))out.push("HDR");if(/4k|uhd/.test(t))out.push("4K UHD");if(/oled/.test(t))out.push("OLED");if(/qled/.test(t))out.push("QLED");if(/no frost|bezszron/.test(t))out.push("No Frost");if(/air fry/.test(t))out.push("Air Fry");if(/wifi|wi-fi/.test(t))out.push("WiFi");if(/bluetooth/.test(t))out.push("Bluetooth");if(/1200/.test(t))out.push("1200 obr.");if(/8 kg|8kg/.test(t))out.push("8 kg");return [...new Set(out)]}

async function dashboard(){const d=await load();stats.innerHTML=`<div class="admin-card"><b>${d.products.length}</b><p>produktów</p></div><div class="admin-card"><b>${d.categories.length}</b><p>kategorii</p></div><div class="admin-card"><b>${d.homeSections.length}</b><p>sekcji strony</p></div><div class="admin-card"><b>${d.brands.length}</b><p>marek</p></div>`}
async function homePage(){const d=await load();sections.innerHTML=d.homeSections.sort((a,b)=>a.order-b.order).map(s=>`<div class="admin-card"><b>${s.active?'🟢':'⚪'} ${s.title}</b><p>${s.id} · kolejność ${s.order}</p><button onclick="toggleSection('${s.id}')">${s.active?'Ukryj':'Aktywuj'}</button></div>`).join("")}
async function toggleSection(id){const d=await load();const s=d.homeSections.find(x=>x.id===id);if(s){s.active=!s.active;save(d);homePage()}}
async function settingsPage(){const d=await load();theme.value=d.settings.theme;type.value=d.settings.typography;logo.value=d.settings.logoVariant;saveSettings.onclick=()=>{d.settings.theme=theme.value;d.settings.typography=type.value;d.settings.logoVariant=logo.value;save(d)}}
async function productPage(){const d=await load();productList.innerHTML=d.products.map(p=>`<div class="admin-card"><b>${p.name}</b><p>${p.category} · ${p.price}</p><a href="../product.html?id=${p.id}">Podgląd</a></div>`).join("");cat.innerHTML=d.categories.filter(c=>c.parent).map(c=>`<option value="${c.id}">${c.name}</option>`).join("");parseBtn.onclick=()=>{const parsed=parseProducer(raw.value);features.value=features.value||parsed.features.join(", ");badges.value=badges.value||autoBadges(raw.value+" "+name.value).join(", ");desc.value=desc.value||parsed.description;parserResult.innerHTML=`Parametry: ${Object.keys(parsed.specs).length} · Cechy: ${parsed.features.length} · Badge: ${autoBadges(raw.value+" "+name.value).join(", ")||"brak"}`};saveProduct.onclick=()=>{const parsed=parseProducer(raw.value);const id=slug(name.value);const item={id,name:name.value,category:cat.value,price:price.value,oldPrice:oldPrice.value,discount:discount.value,promo:promo.checked,featured:featured.checked,image:image.value||"assets/products/tv.svg",badges:badges.value.split(",").map(x=>x.trim()).filter(Boolean),features:features.value.split(",").map(x=>x.trim()).filter(Boolean),specs:parsed.specs,description:desc.value||parsed.description,advisor:advisor.value,stock:Number(stock.value||1),active:true};d.products=d.products.filter(p=>p.id!==id);d.products.push(item);save(d);productPage()}}
async function brandsPage(){const d=await load();brandList.innerHTML=d.brands.map(b=>`<div class="admin-card"><b>${b}</b><p>marka w ruchomym pasku</p></div>`).join("");saveBrand.onclick=()=>{if(brandName.value){d.brands.push(brandName.value);save(d);brandsPage()}}}
async function reviewsPage(){const d=await load();reviewList.innerHTML=[...d.reviews.google.map(r=>['Google',r]),...d.reviews.local.map(r=>['Lokalna',r])].map(([t,r])=>`<div class="admin-card"><b>${t} ★★★★★</b><p>${r}</p></div>`).join("");saveReview.onclick=()=>{const type=reviewType.value;d.reviews[type].push(reviewText.value);save(d);reviewsPage()}}
async function mediaPage(){const d=await load();formats.innerHTML=d.smartMediaEngine.supportedFormats.map(x=>`<span class="admin-card"><b>${x.toUpperCase()}</b></span>`).join("");variants.innerHTML=d.smartMediaEngine.variants.map(x=>`<div class="admin-card"><b>${x}</b><p>wariant obrazu</p></div>`).join("")}
async function checklistPage(){const d=await load();checklist.innerHTML=d.releaseChecklist.map(x=>`<div class="admin-card"><b>☑ ${x}</b></div>`).join("")}
